c/openmp_matrix: define inline when using clang 13
clang 13 on Fedora 35 reports:

    In file included from openmp_matrix.c:9:
    /usr/lib64/clang/13.0.0/include/omp.h:484:12: error: unknown type
    name 'inline'
        static inline int omp_is_initial_device(void) { return 1; }
               ^
    1 error generated.

This is caused by compiling with -ansi -fopenmp. Define "inline" in
order to work around this issue.