python/random_prng: support Python 3.2
On Ubuntu 12.04, using Python3 breaks python/random_prng.py:

      File "./random_prng.py", line 227, in self_test
        expected = binascii.unhexlify('b62372ef302216ca153e52f5d3f88dac4b0b09f35a37a2a503bcf57517849e3b')
    TypeError: 'str' does not support the buffer interface

binascii.unhexlify() understands strings with Python 2 and Python>=3.3