Makefile: use - instead of /dev/stdin to compile test x86-16 program
Using /dev/stdin seems to confuse SonarCloud:

    ERROR: Error during SonarScanner execution
    java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /dev/stdin
            at com.sonar.cpp.jni.FileSystemOperations.realPath(FileSystemOperations.java:66)
            at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
            at com.sonar.cpp.fs.CanonicalPathCache.computeIfAbsent(CanonicalPathCache.java:17)
            at com.sonar.cpp.plugin.CFamilySensor.lambda$process$16(CFamilySensor.java:741)
            at com.sonar.cpp.analyzer.ClangDriver.onCapture(ClangDriver.java:342)
            at com.sonar.cpp.analyzer.CompilerDrivers.onCapture(CompilerDrivers.java:35)
            at com.sonar.cpp.plugin.CFamilySensor.lambda$process$17(CFamilySensor.java:747)
    INFO: Final Memory: 99M/337M