machines/debian13: install setuptools and update info
Like commit 4fd0d887a795 ("machines/ubuntu2404: install setuptools"),
Python 3.12 requires setuptools to be installed, on Debian 13.

`python/cffi_example.py` reports:

    Exception: This CFFI feature requires setuptools on Python >= 3.12.
    The setuptools module is missing or non-functional.

While at it, update information about Debian 13 (currently "testing").