machines/debian10: install m4
Rust crate "gmp-mpfr-sys v1.4.0" now requires m4:

    error: failed to run custom build command for `gmp-mpfr-sys v1.4.0`

    Caused by:
      process didn't exit successfully:
    `/shared/rust/target/debug/build/gmp-mpfr-sys-f1dbcc694524aca4/build-script-build`
    (exit code: 101)

    [...]

    checking for suitable m4...
    --- stderr
    configure: error: No usable m4 in $PATH or /usr/5bin (see config.log
    for reasons).
    thread 'main' panicked at 'Program failed with code 1: "sh" "-c"
    "../gmp-src/configure --enable-fat --disable-shared --with-pic"',
    /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gmp-mpfr-sys-1.4.0/build.rs:1146:13
    note: run with `RUST_BACKTRACE=1` environment variable to display a
    backtrace.