Makefile: do not compile Rust projects with old toolchain
On Alpine 3.17 (Rust 1.64.0):

    error[E0658]: use of unstable library feature 'mixed_integer_ops'
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.14/src/tables.rs:407:22
        |
    407 |                 (sum.wrapping_add_signed(isize::from(add)), info)
        |                      ^^^^^^^^^^^^^^^^^^^
        |
        = note: see issue #87840 <https://github.com/rust-lang/rust/issues/87840> for more information

    error[E0658]: use of unstable library feature 'mixed_integer_ops'
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.14/src/tables.rs:702:22
        |
    702 |                 (sum.wrapping_add_signed(isize::from(add)), info)
        |                      ^^^^^^^^^^^^^^^^^^^
        |
        = note: see issue #87840 <https://github.com/rust-lang/rust/issues/87840> for more information

    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `unicode-width` due to 2 previous errors
    warning: build failed, waiting for other jobs to finish...
    make[1]: *** [../rust-makefile.mk:5: all] Error 101
    make: *** [Makefile:180: test] Error 2

Feature mixed_integer_ops was stabilized in Rustc 1.66.0. Crate
unicode-width is actually used by all Rust projects in this repository.