linux/pass_fd: move #pragma out of function
gcc 4.4.5 (Debian Squeeze) does not support #pragma inside functions:

    pass_fd.c: In function 'child1_main':
    pass_fd.c:113: error: #pragma GCC diagnostic not allowed inside
    functions
    pass_fd.c:114: error: #pragma GCC diagnostic not allowed inside
    functions
    pass_fd.c:116: error: #pragma GCC diagnostic not allowed inside
    functions

Moreover it does not support diagnostic stacking:

    pass_fd.c:33: error: expected [error|warning|ignored] after '#pragma
    GCC diagnostic'
    pass_fd.c:168: error: expected [error|warning|ignored] after
    '#pragma GCC diagnostic'

Copy the code from c/float_asm.c to work around this issue.