boot/efi: fix clang warning on ASM clobber list
clang 4.0.0 reports:

    In file included from hello_world_efi.c:23:
    ./efi.h:416:27: error: asm-specifier for input or output variable
    conflicts with asm clobber list
            : "cc", "memory", "%rcx", "%rdx", "%r8", "%r9", "%r10", "%r11");
                              ^
    ./efi.h:432:27: error: asm-specifier for input or output variable
    conflicts with asm clobber list
            : "cc", "memory", "%rcx", "%rdx", "%r8", "%r9", "%r10", "%r11");
                              ^