linux/pulseaudio_echo: use an enum instead of zero
clang 21 on Fedora 43 reports:

    pulseaudio_echo.c:346:49: error: implicit conversion from 'int' to
    enumeration type 'pa_context_flags_t' (aka 'enum pa_context_flags')
    is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
      346 |     error = pa_context_connect(g_context, NULL, 0, NULL);
          |             ~~~~~~~~~~~~~~~~~~                  ^

https://freedesktop.org/software/pulseaudio/doxygen/def_8h.html#abe3b87f73f6de46609b059e10827863b
documents:

    PA_CONTEXT_NOFLAGS
    Flag to pass when no specific options are needed (used to avoid casting)
    Since 0.9.19