windows/no_import/noimport_start: declare all startup functions as noreturn
Mingw64 9.1.0 warns about using less restrictive attributes:

    noimport_start.h:15:14: error: ‘WinMainCRTStartup’ specifies less
    restrictive attribute than its target ‘_start’: ‘noreturn’
    [-Werror=missing-attributes]
       15 | void __cdecl WinMainCRTStartup(void) __attribute__ ((alias("_start")));
          |              ^~~~~~~~~~~~~~~~~
    noimport_start.h:23:14: note: ‘WinMainCRTStartup’ target declared here
       23 | void __cdecl _start(void)
          |              ^~~~~~

    noimport_start.h:16:14: error: ‘mainCRTStartup’ specifies less
    restrictive attribute than its target ‘_start’: ‘noreturn’
    [-Werror=missing-attributes]
       16 | void __cdecl mainCRTStartup(void) __attribute__ ((alias("_start")));
          |              ^~~~~~~~~~~~~~
    noimport_start.h:23:14: note: ‘mainCRTStartup’ target declared here
       23 | void __cdecl _start(void)
          |              ^~~~~~