python/crypto/aes_tests: support Python 3.2
On Ubuntu 12.04, using Python3 breaks python/crypto/aes_tests.py:

      File "./aes_tests.py", line 1969, in unxx
        return binascii.unhexlify(hexvalue)
    TypeError: 'str' does not support the buffer interface

binascii.unhexlify() understands strings with Python 2 and Python>=3.3