Makefile: do not compile rust/download_web with old toolchain
On Debian 12 (Rust 1.63.0):

    error: package `addr2line v0.21.0` cannot be built because it
    requires rustc 1.65 or newer, while the currently active rustc
    version is 1.63.0
    Either upgrade to rustc 1.65 or newer, or use cargo update -p
    addr2line@0.21.0 --precise ver where `ver` is the latest version of
    `addr2line` supporting rustc 1.63.0