python/crypto/dsa_tests: use q to compute the order
In DSA, parameter q is always 160-bit wide, contrary to the private key (x).
The current implementation leads to errors such as:

    DSA-1024 PyCrypto-generated key:
      y(1023) = 0x4f07423c8b130cf58fdf1465c289e6dbc7c24341604719eec76e96c4058d8e3925e3bb5d23c502974efc75ba3f9ee77b340ce6d0bec01fdadd1009d8ad9d5b1c4527ff970878aa5bdc0ad91871cc48173810c444cc68e12a955fd7055bf71f3f9e853f7c73343f6fecb3eacdc19bdc51c653bddae1805c6b77671606551a98b8
      g(1023) = 0x4f6ae814203bbe272bae6924b7223f6d26fb554beb361520336ece1d4199b9724fb00311cc567f183d31e7a10ff6c042e4aaac6eed913e9b5874e17e84856be061b087a6209f340ad0c130538f5bc8d3b705b760a2b9a702b1931ff916674b3cb223789f816be263f32dc2dc5216244a9363266aeb6f773d6d56f629aab8a6bd
      p(1024) = 0xb68a11767df7f4931dc3f9c18f5f961054e3aa6edc84de912fdf99c2212827aef77cc9c04d6ac2ae20aaad647a614073a868dcf3e5f41dec964261aaf327410f54c42252f85d24ac48c7b5a9816f9fa5b9b261989574dcb01b405764814acd35a172c1f8e42f3cde937809b9663dc4e6adc0fd9c0a6a053bd29b868d50880309
      q(160) = 0x84c887add16ec754f0c50f34845382e68dcb9933
      x(151) = 0x55cc25dfc92dab149befdb8ba4f43e68d7a31e
      (p-1)/q (865) = 0x15fed5ffcd839aefddffec18695767645b51e6b962e106b441d759f948a191b9916d3e7157a72386a01ce2c77d95c4043b474643a5dc5c393432be6059a351f57edc32e1e2d043e50a6062f07b8c785152f4a42ff9f1cf5db6e0f46340e2d2fca5550e8c5a188075693c640d8

    [WARNING] The generated order in 19-byte long instead of 20!
    (...)
    Traceback (most recent call last):
      File "./dsa_tests.py", line 498, in <module>
        sys.exit(main())
      File "./dsa_tests.py", line 489, in main
        if not run_pycrypto_test(args.bits, args.color):
      File "./dsa_tests.py", line 239, in run_pycrypto_test
        verifier.verify(h_obj, encode_bigint_be(r, key_order_bytes) + encode_bigint_be(s, key_order_bytes))
      File "/usr/lib/python3.7/site-packages/Crypto/Signature/DSS.py", line 166, in verify
        raise ValueError("The signature is not authentic")
    ValueError: The signature is not authentic