linux/pass_fd: ignore clang -Wcast-align
On Alpine 3.3, clang reports the following error:

pass_fd.c:112:51: error: cast from 'unsigned char *' to 'struct cmsghdr
*' increases required alignment from 1 to 4 [-Werror,-Wcast-align]
    for (cmsg = CMSG_FIRSTHDR(&msg); cmsg; cmsg = CMSG_NXTHDR(&msg, cmsg)) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/socket.h:267:10: note: expanded from macro 'CMSG_NXTHDR'
        ((struct cmsghdr *)__CMSG_NEXT(cmsg))))
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~