c/find_aes_key: clang 9.0.0 introduced _rotr intrisics
clang now warns on Fedora 31:

    find_aes_key.c:109:17: error: conflicting types for '__rord'
    static uint32_t _rotr(uint32_t x, int n)
                    ^
    /usr/lib64/clang/9.0.0/include/ia32intrin.h:357:20: note: expanded
    from macro '_rotr'
    #define _rotr(a,b) __rord((a), (b))
                       ^
    /usr/lib64/clang/9.0.0/include/ia32intrin.h:330:1: note: previous
    definition is here
    __rord(unsigned int __X, int __C) {
    ^