Makefile: do not compile rust/check_linux_pass with old toolchain
On Alpine 3.14 (Rust 1.52):

    error: failed to parse manifest at
    `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.5.0/Cargo.toml`

    Caused by:
      failed to parse the `edition` key

    Caused by:
      this version of Cargo is older than the `2021` edition, and only
      supports `2015` and `2018` editions.

On Alpine 3.15 (Rust 1.56):

    error: package `byteorder v1.5.0` cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.56.1