c/openmp_matrix: test OpenMP availability with LDFLAGS
LDFLAGS=-Wl,-as-needed,-no-undefined mat change things on some
distributions.

For example Fedora 26 requires linking with libdl with using OpenMP on
x86-32, otherwise linking fails:

    /usr/lib/gcc/x86_64-redhat-linux/7/32/libgomp.a(target.o): In function `gomp_target_init':
    (.text+0x6bf): undefined reference to `dlopen'
    /usr/lib/gcc/x86_64-redhat-linux/7/32/libgomp.a(target.o): In function `gomp_target_init':
    (.text+0x6da): undefined reference to `dlsym'
    /usr/lib/gcc/x86_64-redhat-linux/7/32/libgomp.a(target.o): In function `gomp_target_init':
    (.text+0x711): undefined reference to `dlclose'