windows/virtual_mem: use UINT_PTR instead of ULONG_PTR with PRIxPTR format
On Ubuntu 12.04 using x86-32 MinGW-W64 gcc, the follwoing errors are
reported:

    virtual_mem.c: In function 'main':
    virtual_mem.c:281:17: error: format '%x' expects argument of type
    'unsigned int', but argument 2 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:281:17: error: format '%x' expects argument of type
    'unsigned int', but argument 3 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:301:21: error: format '%x' expects argument of type
    'unsigned int', but argument 2 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:329:17: error: format '%x' expects argument of type
    'unsigned int', but argument 2 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:329:17: error: format '%x' expects argument of type
    'unsigned int', but argument 3 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:356:17: error: format '%x' expects argument of type
    'unsigned int', but argument 2 has type 'long unsigned int'
    [-Werror=format]
    virtual_mem.c:359:17: error: format '%x' expects argument of type
    'unsigned int', but argument 2 has type 'long unsigned int'
    [-Werror=format]