machines/ubuntu1604: remove Cargo and Rust
When trying to build a Rust project on Ubuntu 16.04, `cargo build` fails:

        Updating crates.io index
    error: failed to get `clap` as a dependency of package `asymkeyfind v0.1.0 (/shared/rust/asymkeyfind)`

    Caused by:
      failed to load source for dependency `clap`

    Caused by:
      Unable to update registry `https://github.com/rust-lang/crates.io-index`

    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`

    Caused by:
      error reading from the zlib stream; class=Zlib (5)

As Cargo is broken there, do not install it.