Makefile: do not compile rust/asymkeyfind with old toolchain
On Alpine 3.18 (Rust 1.71.1):

      Downloaded rug v1.28.0
    error: failed to download replaced source registry `crates-io`

    Caused by:
      failed to parse manifest at `/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rug-1.28.0/Cargo.toml`

    Caused by:
      failed to parse the `edition` key

    Caused by:
      this version of Cargo is older than the `2024` edition, and only
      supports `2015`, `2018`, and `2021` editions.
    make[1]: *** [../rust-makefile.mk:5: all] Error 101

On Alpine 3.21 (Rust 1.78.0):

      Downloaded rug v1.28.0
    error: failed to parse manifest at `/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rug-1.28.0/Cargo.toml`

    Caused by:
      feature `edition2024` is required

      The package requires the Cargo feature called `edition2024`, but
      that feature is not stabilized in this version of Cargo (1.78.0).
      Consider trying a newer version of Cargo (this may require the
      nightly release).
      See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024
      for more information about the status of this feature.