c/gtk_alpha_window: disable -Wcast-function-type-strict from clang 16.0
clang 16.0 reports in Glib 2.0 headers used by Gtk+ 3.0:

    In file included from gtk_alpha_window.c:10:
    In file included from /usr/include/gtk-3.0/gdk/gdk.h:30:
    In file included from /usr/include/gtk-3.0/gdk/gdkconfig.h:8:
    In file included from /usr/include/glib-2.0/glib.h:117:
    /usr/include/glib-2.0/glib/glib-autocleanups.h:47:1: error: cast
    from 'void (*)(GAsyncQueue *)' (aka 'void (*)(struct _GAsyncQueue *)')
    to 'void (*)(void)' converts to incompatible function type
    [-Werror,-Wcast-function-type-strict]
    G_DEFINE_AUTOPTR_CLEANUP_FUNC(GAsyncQueue, g_async_queue_unref)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    /usr/include/glib-2.0/glib/gmacros.h:1371:3: note: expanded from
    macro 'G_DEFINE_AUTOPTR_CLEANUP_FUNC'
      _GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS(TypeName, TypeName, func)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    /usr/include/glib-2.0/glib/gmacros.h:1359:47: note: expanded from
    macro '_GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS'
        { g_list_free_full (*_l, (GDestroyNotify) (void(*)(void)) cleanup); }                                       \
                                                  ^~~~~~~~~~~~~~~~~~~~~~~

Silence this warning.