python/crypto/ec_tests: replace hashlib.new('ripemd160') with PyCryptodome
ripemd160 is broken since Fedora 36 (Python 3.10.1 with OpenSSL 3.0)

    $ openssl list -digest-algorithms
    ...
    RIPEMD160

    $ python3
    >>> import hashlib
    >>> 'ripemd160' in hashlib.algorithms_available
    True
    >>> h = hashlib.new('ripemd160')
    Traceback (most recent call last):
      File "/usr/lib64/python3.10/hashlib.py", line 160, in __hash_new
        return _hashlib.new(name, data, **kwargs)
    ValueError: [digital envelope routines] initialization error

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python3.10/hashlib.py", line 166, in __hash_new
        return __get_builtin_constructor(name)(data)
      File "/usr/lib64/python3.10/hashlib.py", line 123, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type ripemd160

Fortunately PyCryptodome still supports this algorithm, according to
https://pycryptodome.readthedocs.io/en/latest/src/hash/ripemd160.html