python: run tests with Python 3 by default
Python 2 is going to be deprecated soon and causes issues like:

    python ./udp_multihome.py
    Traceback (most recent call last):
      File "./udp_multihome.py", line 46, in <module>
        raise NotImplementedError("socket.recvmsg() not found (need Python >= 3.3)")
    NotImplementedError: socket.recvmsg() not found (need Python >= 3.3)

Nowadays, every system using Python has Python 3 installed. Use
PYTHON=python3 by default.