linux-flags: disable -Wused-but-marked-unused for Fedora 41 clang 18
clang 18.1.3 on Fedora 41 fails to build C programs:

    antidebug.c:135:13: error: 'printf' was marked unused but was used
    [-Werror,-Wused-but-marked-unused]
      135 |             printf("[-] int3 instruction detected at %p\n", (void *)pcode);
          |             ^
    antidebug.c:175:13: error: 'fprintf' was marked unused but was used
    [-Werror,-Wused-but-marked-unused]
      175 |             fprintf(stderr, "[!] sensitive_computation gave an unexpected result.\n");
          |             ^