windows: ignore -Warray-bounds for NtCurrentTeb with mingw-gcc 14
On Fedora 40 with gcc 14.0.1, NtCurrentTeb() leads to:

    /usr/x86_64-w64-mingw32/sys-root/mingw/include/psdk_inc/intrin-impl.h:838:1:
    error: array subscript 0 is outside array bounds of 'long long
    unsigned int[0]' [-Werror=array-bounds=]
      838 | __buildreadseg(__readgsqword, unsigned __int64, "gs", "q")
          | ^~~~~~~~~~~~~~

This is similar as commit fda09cf06a93 ("windows: ignore -Warray-bounds
for NtCurrentTeb with mingw-gcc 13")

Expand to gcc 14 the compiler versions which disable the warning.