linux/modules/mmap_file: `dentry->d_name` was constified in Linux 6.18
Linux 6.18 made field `d_name` of `struct dentry` const in commit
https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=180a9cc3fd6a020746fbd7f97b9b62295a325fd2
"make it easier to catch those who try to modify ->d_name".

Constify `filename` to fix a compiler error triggered due to this, in
Alpine 3.23 running Linux 6.18.5-0-lts:

    mmap_file.c: In function 'mmap_file_open':
    mmap_file.c:110:18: error: assignment discards 'const' qualifier
    from pointer target type [-Werror=discarded-qualifiers]
      110 |         filename = &filp->f_path.dentry->d_name;
          |                  ^