Makefile: do not compile rust/asymkeyfind with old toolchain
rug became incompatible with Alpine 3.13 toolchain (cargo 1.47):

      Downloaded rug v1.19.0
    error: failed to parse manifest at
    `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/rug-1.19.0/Cargo.toml`

    Caused by:
      failed to parse the `edition` key

    Caused by:
      this version of Cargo is older than the `2021` edition, and only
      supports `2015` and `2018` editions.

It also fails on Ubuntu 20.04:

    error: package `rug v1.19.0` cannot be built because it requires
    rustc 1.65 or newer, while the currently active rustc version is
    1.61.0