c/gtk_alpha_window: fix build with clang 7.0
clang 7.0 on Fedora 29 warns about things in Glib-2.0 headers:

    /usr/include/glib-2.0/gio/glistmodel.h:36:1: error:
    'glib_autoptr_cleanup_GObject' was marked unused but was used
    [-Werror,-Wused-but-marked-unused]
    G_DECLARE_INTERFACE(GListModel, g_list_model, G, LIST_MODEL, GObject)
    ^
    /usr/include/glib-2.0/gobject/gtype.h:1572:3: note: expanded from macro 'G_DECLARE_INTERFACE'
      _GLIB_DEFINE_AUTOPTR_CHAINUP (ModuleObjName, PrerequisiteName)                                           \
      ^
    /usr/include/glib-2.0/glib/gmacros.h:491:5: note: expanded from macro '_GLIB_DEFINE_AUTOPTR_CHAINUP'
        _GLIB_AUTOPTR_FUNC_NAME(ParentName) ((ParentName **) _ptr); }                                        \
        ^
    /usr/include/glib-2.0/glib/gmacros.h:480:43: note: expanded from macro '_GLIB_AUTOPTR_FUNC_NAME'
    #define _GLIB_AUTOPTR_FUNC_NAME(TypeName) glib_autoptr_cleanup_##TypeName
                                              ^
    <scratch space>:49:1: note: expanded from here
    glib_autoptr_cleanup_GObject
    ^