Makefile: do not compile rust/download_web with old toolchain
On Alpine 3.18 (Rust 1.71.1):

    error: package `backtrace v0.3.75` cannot be built because it
    requires rustc 1.82.0 or newer, while the currently active rustc
    version is 1.71.1
    Either upgrade to rustc 1.82.0 or newer, or use
    cargo update -p backtrace@0.3.75 --precise ver
    where `ver` is the latest version of `backtrace` supporting rustc 1.71.1