windows/host_info: fix -Wincompatible-pointer-types
Mingw64 in 32-bit mode complains:

    host_info.c: In function ‘wmain’:
    host_info.c:91:28: error: assignment from incompatible pointer type
    [-Werror=incompatible-pointer-types]
         pfnGetNativeSystemInfo = (VOID(*)(LPSYSTEM_INFO)) GetProcAddress(hKernel, "GetNativeSystemInfo");
                                ^

The compiler did not like the missing __attribute__((__stdcall__)).