windows/list_desktop: work around Wine bug 57813
Since Wine 9.22, EnumDesktopWindows can return FALSE without modifying
GetLastError: https://bugs.winehq.org/show_bug.cgi?id=57813

Ignore when such an issue happens, showing that enumeration failed
without propagating the error value:

    $ wine ./list_desktops.exe
    * [WindowStation] WinSta0 (current)
      * [Desktop] Default (current)
        (EnumDesktopWindows failed without setting the Last Error, ignoring Wine bug 57813)
    * [WindowStation] __wineservice_winstation
      * [Desktop] Default