c/float_asm: silence -Wdouble-promotion from clang
With glibc 2.25, isnan() gets expanded to isnanf() for float, isnan()
for double and isnanl() for long double, using a ternary expression.
clang 3.9 does not like this:

    float_asm.c:283:12: error: implicit conversion increases
    floating-point precision: 'float' to 'long double'
    [-Werror,-Wdouble-promotion]
        ok_nan(sqrt_f(-1));
        ~~~~~~~^~~~~~~~~~~

As musl library does not provide isnanf(), use isnan() when isnanf() is
not available.