glossaries/check_sort_order: specify the UTF-8 encoding of the files
On Windows, UTF-8 has to be specified. Otherwise GitHub Actions reports:

    python ./check_sort_order.py
    english.rst: disorder I�2C > IC (I²C needs to come after IC)
    Traceback (most recent call last):
      File "./check_sort_order.py", line 199, in <module>
        sys.exit(0 if check_sort_order_of_all() else 1)
      File "./check_sort_order.py", line 193, in check_sort_order_of_all
        if not check_file_sort_order(file_path):
      File "./check_sort_order.py", line 135, in check_file_sort_order
        for line in stream:
      File "C:\hostedtoolcache\windows\Python\3.8.7\x64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 156: character maps to <undefined>