linux/pass_fd: fix Musl compatibility
When building with Musl 1.1.19 and GCC 8.2.1, the compiler reports some
warnings about the way strncpy is being used:

    pass_fd.c: In function ‘child1_main’:
    pass_fd.c:85:5: error: ‘strncpy’ specified bound 108 equals
    destination size [-Werror=stringop-truncation]
         strncpy(addr.sun_path, sockpath, sizeof(addr.sun_path));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    pass_fd.c: In function ‘child2_main’:
    pass_fd.c:222:9: error: ‘strncpy’ specified bound 108 equals
    destination size [-Werror=stringop-truncation]
             strncpy(addr.sun_path, sockpath, sizeof(addr.sun_path));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Silence the compiler warnings by using size-1.