machines: remove Fedora 20 and Fedora21
Fedora 21 (released in 12/2014) no longer works. yum reports:

    Rpmdb checksum is invalid: dCDPT(pkg checksums): grub2.x86_64 1:2.02-0.13.fc21 - u

As the most recent version of Fedora is 28 now, remove this
dysfunctional machine.

As Fedora 20 also presents issues, remove it too. For example it fails
to install openssl, with:

    Error: Package: 1:openssl-1.0.1e-42.fc20.x86_64 (updates)
       Requires: openssl-libs(x86-64) = 1:1.0.1e-42.fc20
       Installed: 1:openssl-libs-1.0.1e-45.fc20.x86_64 (@fedora-updates-testing/$releasever)
           openssl-libs(x86-64) = 1:1.0.1e-45.fc20
       Available: 1:openssl-libs-1.0.1e-30.fc20.x86_64 (fedora)
           openssl-libs(x86-64) = 1:1.0.1e-30.fc20
       Available: 1:openssl-libs-1.0.1e-42.fc20.x86_64 (updates)
           openssl-libs(x86-64) = 1:1.0.1e-42.fc20