c/gtk_alpha_window: fix draw event implementation with Gtk+ 3
Gtk+ 3 "draw" event uses a callback with cairo_t *cr, not GdkEventExpose
*event. Indeed in the commit which introduced it, the expose event of
the GtkWidget took care of creating the convinient cr in
gtk_widget_real_expose_event():
https://github.com/GNOME/gtk/commit/7108586b16e683910e38bd0eda378df19b1ddbae#diff-b25238031eb6ef7053d8b3d52947cb92R5073

This bug has been detected by this error when compiling with gtk+ 3.21:

    gtk_alpha_window.c: In function 'expose':
    gtk_alpha_window.c:120:5: error: 'gdk_cairo_create' is deprecated:
    Use 'gdk_window_begin_draw_frame() and
    gdk_drawing_context_get_cairo_context()' instead
    [-Werror=deprecated-declarations]
         cr = gdk_cairo_create(window);
         ^~
    In file included from /usr/include/gtk-3.0/gdk/gdk.h:33:0,
                     from gtk_alpha_window.c:10:
    /usr/include/gtk-3.0/gdk/gdkcairo.h:35:12: note: declared here
     cairo_t  * gdk_cairo_create             (GdkWindow          *window);
                ^~~~~~~~~~~~~~~~

... and then the following runtime failure when trying to use
gdk_window_begin_draw_frame():

    (gtk_alpha_window.bin:735): Gdk-CRITICAL **: The window
    0x323fb1814c0 already has a drawing context. You cannot call
    gdk_window_begin_draw_frame() without calling
    gdk_window_end_draw_frame() first.