machines/fedora30: do not install Wine because it is buggy
It fails with weird error messages:

    WINEARCH=win64 wine ./security_descriptor.exe
    ...
    Security Descriptor of "CURRENT_USER\Environment":
    GetNamedSecurityInfo: error 2, File not found

    WINEARCH=win64 wine ./subprocess_cmd.exe
    0076:err:module:__wine_process_init failed to load L"C:\\windows\\system32\\wineboot.exe", error c0000018
    0074:err:environ:run_wineboot failed to start wineboot c0000018
    007a:err:module:__wine_process_init failed to load L"C:\\windows\\system32\\wineboot.exe", error c0000018
    0078:err:environ:run_wineboot failed to start wineboot c0000018
    0078:fixme:winediag:__wine_start_process Wine Staging 5.0 is a testing version containing experimental patches.
    0078:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
    CreateProcess(cmd): error 2, File not found