machines/fedora41: install openssl-devel-engine
Building rust/download_web with curl requires
/usr/include/openssl/engine.h, now provided in package
openssl-devel-engine:

    The following warnings were emitted during compilation:

    warning: curl-sys@0.4.74+curl-8.9.0: curl/lib/vtls/openssl.c:103:10: fatal error: openssl/engine.h: No such file or directory
    warning: curl-sys@0.4.74+curl-8.9.0:   103 | #include <openssl/engine.h>
    warning: curl-sys@0.4.74+curl-8.9.0:       |          ^~~~~~~~~~~~~~~~~~
    warning: curl-sys@0.4.74+curl-8.9.0: compilation terminated.

    error: failed to run custom build command for `curl-sys v0.4.74+curl-8.9.0`