verification/ackermann: use Search instead of SearchAbout
Coq 8.11.0 (March 2020) warns:

    Warning: The SearchAbout command is deprecated. Please use Search instead

Coq 8.12.0 (August 2020) actually fails:

    Error: Syntax error: illegal begin of vernac.