machines/fedora40: install setuptools
Testing Python CFFI fails without setuptools:

    python3 ./cffi_example.py
    getuid() = 0
    getgid() = 0
    getpid() = 3973
    Traceback (most recent call last):
      File "/usr/lib64/python3.12/site-packages/cffi/_shimmed_dist_utils.py", line 12, in <module>
        import setuptools
    ModuleNotFoundError: No module named 'setuptools'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/shared/python/./cffi_example.py", line 53, in <module>
        libv = ffi.verify('const size_t LONG_SIZE = sizeof(long);')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/site-packages/cffi/api.py", line 468, in verify
        lib = self.verifier.load_library()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/site-packages/cffi/verifier.py", line 105, in load_library
        self._compile_module()
      File "/usr/lib64/python3.12/site-packages/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
                                                     ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/site-packages/cffi/verifier.py", line 126, in get_extension
        return ffiplatform.get_extension(sourcename, modname, **self.kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/site-packages/cffi/ffiplatform.py", line 9, in get_extension
        from cffi._shimmed_dist_utils import Extension
      File "/usr/lib64/python3.12/site-packages/cffi/_shimmed_dist_utils.py", line 16, in <module>
        raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
    Exception: This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.