machines/archlinux: ensure OpenSSL is up to date
hashlib.pbkdf2_hmac did not exist in the new container. To get a clear
error message besides what the official documentation says in
https://docs.python.org/3.12/library/hashlib.html#hashlib.pbkdf2_hmac

> Changed in version 3.12: Function now only available when Python is
> built with OpenSSL. The slow pure Python implementation has been
> removed.

... it is possible to run:

    $ python3
    Python 3.13.1 (main, Dec  4 2024, 18:05:56) [GCC 14.2.1 20240910] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from _hashlib import pbkdf2_hmac
    Traceback (most recent call last):
      File "<python-input-0>", line 1, in <module>
        from _hashlib import pbkdf2_hmac
    ImportError: /usr/lib/libcrypto.so.3: version `OPENSSL_3.4.0' not
    found (required by
    /usr/lib/python3.13/lib-dynload/_hashlib.cpython-313-x86_64-linux-gnu.so)

    $ ldd /usr/lib/python3.13/lib-dynload/_hashlib.cpython-313-x86_64-linux-gnu.so
    /usr/lib/python3.13/lib-dynload/_hashlib.cpython-313-x86_64-linux-gnu.so: /usr/lib/libcrypto.so.3: version `OPENSSL_3.4.0' not found (required by /usr/lib/python3.13/lib-dynload/_hashlib.cpython-313-x86_64-linux-gnu.so)
            linux-vdso.so.1 (0x00007f8d5d31c000)
            libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f8d5ce29000)
            libc.so.6 => /usr/lib/libc.so.6 (0x00007f8d5cc37000)
            /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8d5d31e000)

Indeed, openssl 3.3.1-1 was installed and 3.4.0-1 was available.

Fix such an issue by installing the latest version of OpenSSL too.

While at it, update the Arch Linux versions.