.github/workflows/sonarcloud: used JDK 21
Sonarcloud reports:

    WARN: The version of Java (11.0.3) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
    INFO: ------------------------------------------------------------------------
    INFO: EXECUTION FAILURE
    INFO: ------------------------------------------------------------------------
    ERROR: Error during SonarScanner execution

    The version of Java (11.0.3) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
    As a temporary measure, you can set the property 'sonar.scanner.force-deprecated-java-version' to 'true' to continue using Java 11.0.3
    This workaround will only be effective until January 28, 2024. After this date, all scans using the deprecated Java 11 will fail.

    ERROR:
    ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

Use JDK 21 and update SonarScanner to use the right JDK distribution.