c/x86-umip-recovery: silence gcc 11 -Wunused-value
On Fedora 34, gcc 11.0.0 reports:

    x86-segments.c: In function ‘print_segments’:
    x86-umip-recovery.h:54:27: error: right-hand operand of comma
    expression has no effect [-Werror=unused-value]
       54 |     if (g_umip_in_section = 1, sigsetjmp(g_umip_jmpbuf, SIGSEGV)) { \
          |         ~~~~~~~~~~~~~~~~~~^~~
    x86-segments.c:207:5: note: in expansion of macro ‘UMIP_SECTION_START’
      207 |     UMIP_SECTION_START("SLDT")
          |     ^~~~~~~~~~~~~~~~~~

Fix this by introducing a real block instead of a comma expression.