c/float_asm: fix compilation with clang 3.8
clang complains:

    error: implicit conversion increases floating-point precision:
    'float' to 'double' [-Werror,-Wdouble-promotion]

because 1.e-6 is a double.  Add an "f" to make it a float.