Makefile: introduce pkg-config-with-options
Test whether a library is both installed and usable in order to handle
systems where using clang with musl-specific headers may produce some
incompatibilites.

For example on Alpine 3.5 with SDL2:

    In file included from sdl_v4l_video.c:23:
    In file included from /usr/include/SDL2/SDL.h:38:
    /usr/include/SDL2/SDL_cpuinfo.h:53:10: fatal error: 'mmintrin.h'
    file not found
    #include <mmintrin.h>
             ^