linux/crypto_socket: disable -Wstrict-aliasing
gcc complains about code which breaks the rules of anti-aliasing of
pointers:

    crypto_socket.c: In function ‘test_aes_xts_enc’:
    crypto_socket.c:328:5: error: dereferencing type-punned pointer will
    break strict-aliasing rules [-Werror=strict-aliasing]
         *(uint32_t *)CMSG_DATA(cmsg) = ALG_OP_ENCRYPT;
         ^
    crypto_socket.c: In function ‘test_aes_cbc_dec’:
    crypto_socket.c:466:5: error: dereferencing type-punned pointer will
    break strict-aliasing rules [-Werror=strict-aliasing]
         *(uint32_t *)CMSG_DATA(cmsg) = ALG_OP_DECRYPT;
         ^