linux/nolibc: test -m32 availability with errno.h instead of linux/types.h
This fixes build on systems where 32-bit headers are missing:

    In file included from /usr/include/features.h:388:0,
                     from /usr/include/errno.h:28,
                     from nolibc-syscall-linux.h:9,
                     from print_args.c:4:
    /usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h:
    No such file or directory
     # include <gnu/stubs-32.h>
                               ^
    compilation terminated.